package com.github.cameltooling.lspclient;

import java.io.File;
import javax.swing.JFileChooser;
import org.openide.util.NbPreferences;

/**
 * Class with user interface used in Apache Camel Language Client.
 * 
 * @author Filip Pospisil - xpospi0f
 */
final class ApacheCamelPanel extends javax.swing.JPanel {

    private final ApacheCamelOptionsPanelController controller;

    ApacheCamelPanel(ApacheCamelOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ApacheCamelLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        versionField = new javax.swing.JTextField();
        providerLabel = new javax.swing.JLabel();
        providerCombo = new javax.swing.JComboBox<>();
        componentsLabel = new javax.swing.JLabel();
        componentsTextArea = new java.awt.TextArea();
        kafkaLabel = new javax.swing.JLabel();
        kafkaField = new javax.swing.JTextField();
        resetDefaultButton = new javax.swing.JButton();
        advancedCheckBox = new javax.swing.JCheckBox();
        customServerTextField = new javax.swing.JTextField();
        customServerButton = new javax.swing.JButton();
        customServerCheckBox = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(ApacheCamelLabel, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.ApacheCamelLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(descriptionLabel, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.descriptionLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(versionLabel, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.versionLabel.text")); // NOI18N

        versionField.setText(org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.versionField.text")); // NOI18N
        versionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versionFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(providerLabel, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.providerLabel.text")); // NOI18N

        providerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Spring Boot", "Quarkus", "Karaf" }));
        providerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerComboActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(componentsLabel, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.componentsLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(kafkaLabel, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.kafkaLabel.text")); // NOI18N

        kafkaField.setText(org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.kafkaField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(resetDefaultButton, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.resetDefaultButton.text")); // NOI18N
        resetDefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDefaultButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(advancedCheckBox, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.advancedCheckBox.text")); // NOI18N
        advancedCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.advancedCheckBox.toolTipText")); // NOI18N
        advancedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedCheckBoxActionPerformed(evt);
            }
        });

        customServerTextField.setText(org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.customServerTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(customServerButton, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.customServerButton.text")); // NOI18N
        customServerButton.setToolTipText(org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.customServerButton.toolTipText")); // NOI18N
        customServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customServerButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(customServerCheckBox, org.openide.util.NbBundle.getMessage(ApacheCamelPanel.class, "ApacheCamelPanel.customServerCheckBox.text")); // NOI18N
        customServerCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customServerCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kafkaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kafkaField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(customServerCheckBox))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customServerTextField)
                                .addGap(18, 18, 18)
                                .addComponent(customServerButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(advancedCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetDefaultButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descriptionLabel)
                                    .addComponent(ApacheCamelLabel))
                                .addGap(0, 110, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(providerLabel)
                                    .addComponent(versionLabel)
                                    .addComponent(componentsLabel))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(versionField)
                                    .addComponent(componentsTextArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(providerCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ApacheCamelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providerLabel)
                    .addComponent(providerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(componentsLabel)
                    .addComponent(componentsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kafkaLabel)
                    .addComponent(kafkaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advancedCheckBox)
                    .addComponent(resetDefaultButton))
                .addGap(37, 37, 37)
                .addComponent(customServerCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customServerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customServerButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void providerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerComboActionPerformed

    private void resetDefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDefaultButtonActionPerformed
        // basic
        versionField.setText(ProcessPreferences.VERSION_DEFAULT);
        providerCombo.setSelectedIndex(ProcessPreferences.PROVIDER_DEFAULT);
        componentsTextArea.setText(ProcessPreferences.COMPONENTS_DEFAULT);
        kafkaField.setText(ProcessPreferences.KAFKA_DEFAULT);

        // advanced
        advancedCheckBox.setSelected(ProcessPreferences.ADVANCED_FLAG_DEFAULT);
  
        changeVisibilityOfAdvanced(ProcessPreferences.ADVANCED_FLAG_DEFAULT);
    }//GEN-LAST:event_resetDefaultButtonActionPerformed

    private void versionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_versionFieldActionPerformed

    private void advancedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedCheckBoxActionPerformed
        changeVisibilityOfAdvanced(advancedCheckBox.isSelected());
    }//GEN-LAST:event_advancedCheckBoxActionPerformed

    /**
     * 
     */
    private void customServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customServerButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        customServerTextField.setText(f.getAbsolutePath());
    }//GEN-LAST:event_customServerButtonActionPerformed

    private void customServerCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customServerCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customServerCheckBoxActionPerformed

    /**
     * 
     * @param visible 
     */
    void changeVisibilityOfAdvanced(boolean visible) {        
        // custom lsp server
        customServerCheckBox.setVisible(visible); // label
        customServerTextField.setVisible(visible); // path
        customServerButton.setVisible(visible); // choose button
    }

    /**
     * Loads preferences for client.
     */
    void load() {
        // basic
        versionField.setText(NbPreferences.forModule(ApacheCamelPanel.class).get("versionPreference", ProcessPreferences.VERSION_DEFAULT)); // version
        providerCombo.setSelectedIndex(NbPreferences.forModule(ApacheCamelPanel.class).getInt("providerPreference", ProcessPreferences.PROVIDER_DEFAULT)); // provider        
        componentsTextArea.setText(NbPreferences.forModule(ApacheCamelPanel.class).get("additionalComponents", ProcessPreferences.COMPONENTS_DEFAULT)); // additional component 
        kafkaField.setText(NbPreferences.forModule(ApacheCamelPanel.class).get("kafkaPreference", ProcessPreferences.KAFKA_DEFAULT)); // kafka
        
        // advanced options
        advancedCheckBox.setSelected(NbPreferences.forModule(ApacheCamelPanel.class).getBoolean("advancedPreference", ProcessPreferences.ADVANCED_FLAG_DEFAULT));
        changeVisibilityOfAdvanced(NbPreferences.forModule(ApacheCamelPanel.class).getBoolean("advancedPreference", ProcessPreferences.ADVANCED_FLAG_DEFAULT));
        
        // Custom LSP 
        customServerCheckBox.setSelected(NbPreferences.forModule(ApacheCamelPanel.class).getBoolean("useCustomServer", ProcessPreferences.CUSTOM_SERVER_FLAG_DEFAULT));
        customServerTextField.setText(NbPreferences.forModule(ApacheCamelPanel.class).get("customServerPath", ProcessPreferences.CUSTOM_SERVER_PATH_DEFAULT));

    }

    /**
     * Store preferences for client. 
     */
    void store() {

        // basic
        NbPreferences.forModule(ApacheCamelPanel.class).put("versionPreference", versionField.getText()); // version
        NbPreferences.forModule(ApacheCamelPanel.class).putInt("providerPreference", providerCombo.getSelectedIndex()); // provider
        NbPreferences.forModule(ApacheCamelPanel.class).put("additionalComponents", componentsTextArea.getText()); // additional component
        NbPreferences.forModule(ApacheCamelPanel.class).put("kafkaPreference", kafkaField.getText()); // kafka

        // advanced options
        NbPreferences.forModule(ApacheCamelPanel.class).putBoolean("advancedPreference", advancedCheckBox.isSelected()); // show advanced check box

        // use custom lsp server
        NbPreferences.forModule(ApacheCamelPanel.class).putBoolean("useCustomServer", customServerCheckBox.isSelected()); // use custom check box
        NbPreferences.forModule(ApacheCamelPanel.class).put("customServerPath", customServerTextField.getText()); // path to server
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApacheCamelLabel;
    private javax.swing.JCheckBox advancedCheckBox;
    private javax.swing.JLabel componentsLabel;
    private java.awt.TextArea componentsTextArea;
    private javax.swing.JButton customServerButton;
    private javax.swing.JCheckBox customServerCheckBox;
    private javax.swing.JTextField customServerTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField kafkaField;
    private javax.swing.JLabel kafkaLabel;
    private javax.swing.JComboBox<String> providerCombo;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JButton resetDefaultButton;
    private javax.swing.JTextField versionField;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
